-- MySQL Script generated by MySQL Workbench
-- qui 10 set 2020 12:19:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_hatedspotshare
-- -----------------------------------------------------
-- Start the integration between backend and database
-- 

-- -----------------------------------------------------
-- Schema db_hatedspotshare
--
-- Start the integration between backend and database
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_hatedspotshare` ;
USE `db_hatedspotshare` ;

-- -----------------------------------------------------
-- Table `db_hatedspotshare`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_hatedspotshare`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(12) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` CHAR(32) NOT NULL,
  `permission` TINYINT(1) UNSIGNED NOT NULL COMMENT '0 - Adm\n1 - Common',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_hatedspotshare`.`features`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_hatedspotshare`.`features` (
  `id` TINYINT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_hatedspotshare`.`spots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_hatedspotshare`.`spots` (
  `code` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `image` TEXT NOT NULL,
  `country` VARCHAR(50) NOT NULL,
  `state` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `neighborhood` VARCHAR(50) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `number` INT(5) UNSIGNED NULL,
  `users_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `fk_spots_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_spots_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `db_hatedspotshare`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_hatedspotshare`.`spots_has_features`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_hatedspotshare`.`spots_has_features` (
  `spots_code` INT UNSIGNED NOT NULL,
  `features_id` TINYINT UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`spots_code`, `features_id`),
  INDEX `fk_spots_has_features_features1_idx` (`features_id` ASC),
  INDEX `fk_spots_has_features_spots1_idx` (`spots_code` ASC),
  CONSTRAINT `fk_spots_has_features_spots1`
    FOREIGN KEY (`spots_code`)
    REFERENCES `db_hatedspotshare`.`spots` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spots_has_features_features1`
    FOREIGN KEY (`features_id`)
    REFERENCES `db_hatedspotshare`.`features` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
